name = "daniyusk/quicknet"
version = "0.3.5"
description = "Highly optimized networking library for Roblox"
license = "MIT"
authors = ["daniyusk"]
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/QuickNet/init.luau"
