name = "daniyusk/quicknet"
version = "0.3.5"
realm = "shared"
description = "Highly optimized networking library for Roblox"
authors = ["daniyusk"]
targets = { lib = "src/QuickNet.luau" }
includes = ["src/QuickNet", "src/QuickNet.luau", "pesde.toml"]
